
import type { Metadata } from 'next'


import { MenuBar } from '../components/MenuBar';
import { Footer } from '../components/Footer';
import { karla, nunito } from '@/assets/fonts';


import '../assets/styles/globals.scss'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-bs-theme="dark">
      <body className={`${ karla.variable } ${ nunito.variable }`}>
        <MenuBar/>
        <div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
