
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import 'bootstrap/dist/css/bootstrap.min.css';
import { MenuBar } from '../components/MenuBar';
import { Footer } from '../components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-bs-theme="dark">
      <body className={inter.className}>
        <MenuBar/>
        <div className="border border-danger">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
